"""Initial Migration

Revision ID: aa4ab8d8db55
Revises: edf7f94b291a
Create Date: 2021-08-17 20:11:15.058914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4ab8d8db55'
down_revision = 'edf7f94b291a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch', sa.Text(), nullable=False))
    op.drop_column('pitches', 'post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('post', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('pitches', 'pitch')
    # ### end Alembic commands ###
