"""Initial Migration

Revision ID: bf715212e713
Revises: 687b57a0f5e9
Create Date: 2021-08-17 17:25:05.903334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf715212e713'
down_revision = '687b57a0f5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secure_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'secure_password')
    # ### end Alembic commands ###
