"""Initial Migration

Revision ID: edf7f94b291a
Revises: bf715212e713
Create Date: 2021-08-17 18:05:43.521962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf7f94b291a'
down_revision = 'bf715212e713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.drop_column('users', 'secure_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secure_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
