"""Initial Migration

Revision ID: f8d50156c564
Revises: 6b51cbca813e
Create Date: 2021-08-25 21:05:07.554815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8d50156c564'
down_revision = '6b51cbca813e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pitches', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('pitches', 'pitch',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('pitches', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('pitches', 'pitch',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('pitches', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
